/* FactoryFlow optimizer: isolated UI, existing JWT only, no persistent demo fallback. */
(()=>{'use strict';
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=x=>x?new Date(x).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'Não informado';
 const mins=x=>x==null?'Não medido':`${(x/60).toFixed(1)} h`;
 const names={pcp_liberacao:'PCP · Liberação',pesagem:'Pesagem',producao:'Produção / Mistura',coloracao:'Coloração',laboratorio:'Laboratório',envase:'Envase',coloracao_revisao:'Coloração · Revisão',laboratorio_revisao:'Laboratório · Revisão',coloracao_amostras:'Coloração · Amostras',laboratorio_amostras:'Laboratório · Amostras',envase_produzir:'Envase · Produzir',envase_enlatamento:'Envase · Enlatamento',pronto:'Pronto para entrega',entrega:'Em rota',entregue:'Entregue'};
 const risks={atrasada:'Atrasada',risco:'Previsão após prazo',atencao:'Próxima de atrasar',no_prazo:'No prazo',bloqueada:'Bloqueada',sem_prazo:'Sem prazo',concluida:'Concluída'};
 let data=null,tab='queue',search='',risk='',sector='',root,simulated=false,busy=false;
 const demo=!!window.OPTIMIZER_DEMO;
 function base(){if(demo)return '';return (typeof resolveFactoryFlowApiBase==='function'?resolveFactoryFlowApiBase():typeof getFactoryFlowApiBase==='function'?getFactoryFlowApiBase():window.API_BASE||'https://app-producao-backend-production.up.railway.app').replace(/\/$/,'');}
 async function api(path,method='GET',body,key){const token=sessionStorage.getItem('ff_token')||localStorage.getItem('ff_token');const r=await fetch(`${base()}/api/optimizer${path}`,{method,cache:'no-store',headers:{'Content-Type':'application/json',...(!demo&&token?{Authorization:`Bearer ${token}`}:{ }),...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});let j;try{j=await r.json();}catch{throw Error('O servidor não devolveu uma resposta válida.');}if(!r.ok)throw Error(r.status===401?'Sessão expirada. Entre novamente no FactoryFlow.':j.error||'Não foi possível carregar o painel.');return j;}
 function message(msg,error=false){const box=root.querySelector('#optMessage');box.className='opt-notice'+(error?' opt-error':'');box.textContent=msg;box.hidden=false;}
 async function action(fn){if(busy)return;busy=true;try{await fn();}catch(e){message(e.message,true);}finally{busy=false;}}
 function shell(){root.innerHTML=`<section class="opt"><div class="opt-head"><div><div class="opt-eyebrow">Induscolor / PCP</div><h1>Ritmo da produção</h1><p class="opt-muted">Fila, capacidade e tempo de atravessamento</p></div><div class="opt-tools"><button data-action="snapshot">Registrar previsão</button><button class="opt-primary" data-action="refresh">Atualizar plano</button></div></div><div id="optMessage" role="status" hidden></div><div id="optBody"><p class="opt-empty">Calculando a fila e a capacidade…</p></div><dialog id="optDetail" aria-label="Detalhes da ordem"></dialog></section>`;
 root.querySelector('[data-action=refresh]').onclick=()=>action(load);root.querySelector('[data-action=snapshot]').onclick=()=>action(async()=>{if(simulated)throw Error('Atualize o plano real antes de registrar a previsão.');const r=await api('/snapshots','POST',{},crypto.randomUUID());message(`Previsão ${r.id} registrada com as amostras de tempo disponíveis.`);});}
 async function load(){const d=await api('/dashboard');data=d;simulated=false;render();}
 window.renderOptimizer=async()=>{root=document.getElementById('pageOptimizer');if(!root)return;shell();await action(load);};
 function render(){
 const s=data.summary;root.querySelector('#optBody').innerHTML=`${demo?'<div class="opt-notice">DEMONSTRAÇÃO · OPs e tempos fictícios. Nenhum aplicativo ou banco de produção está conectado a esta prévia.</div>':''}${simulated?'<div class="opt-notice">SIMULAÇÃO · A capacidade abaixo ainda não foi salva.</div>':''}${data.warnings.map(w=>`<div class="opt-notice">${esc(w)}</div>`).join('')}<div class="opt-kpis">${[[s.open,'OPs abertas'],[s.urgent,'Urgentes'],[s.late,'Atrasadas'],[s.atRisk,'Em risco / atenção'],[s.blocked,'Bloqueadas'],[s.withoutDue,'Sem prazo']].map(([v,l])=>`<div class="opt-card"><small>${l}</small><span class="opt-number">${v}</span></div>`).join('')}</div><div class="opt-tabs" role="tablist" aria-label="Visões do planejamento">${[['queue','Fila inteligente'],['capacity','Carga por setor'],['recommend','Reprogramação'],['times','Tempos reais'],['settings','Capacidade & regras']].map(([k,l])=>`<button role="tab" aria-selected="${tab===k}" data-tab="${k}">${l}</button>`).join('')}</div><div id="optView" role="tabpanel"></div><div class="opt-foot"><span>Atualizado ${date(data.generatedAt)} · Horário de Brasília</span><span>${esc(data.version)} · Estimativa por regras e histórico</span></div>`;
 root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});view();}
 function view(){const v=root.querySelector('#optView');if(tab==='queue')queue(v);else if(tab==='capacity')capacity(v);else if(tab==='recommend')recommend(v);else if(tab==='times')times(v);else settings(v);}
 function filtered(){return data.queue.filter(o=>!o.done&&(!risk||o.risk===risk)&&(!sector||o.sector===sector)&&`${o.op} ${o.name} ${o.client}`.toLowerCase().includes(search.toLowerCase()));}
 function queue(v){v.innerHTML=`<div class="opt-tools"><input id="optSearch" aria-label="Buscar OP, produto ou cliente" placeholder="Buscar OP, produto ou cliente" value="${esc(search)}"><select id="optRisk" aria-label="Filtrar situação"><option value="">Todas as situações</option>${Object.entries(risks).map(([k,l])=>`<option value="${k}" ${risk===k?'selected':''}>${l}</option>`).join('')}</select><select id="optSector" aria-label="Filtrar setor"><option value="">Todos os setores</option>${Object.entries(names).map(([k,l])=>`<option value="${k}" ${sector===k?'selected':''}>${l}</option>`).join('')}</select></div><p class="opt-muted">Ordenação: urgência + folga do prazo + envelhecimento + ajuste PCP. Dependências e bloqueios impedem a programação.</p><div id="optRows"></div>`;
 v.querySelector('#optSearch').oninput=e=>{search=e.target.value;rows();};v.querySelector('#optRisk').onchange=e=>{risk=e.target.value;rows();};v.querySelector('#optSector').onchange=e=>{sector=e.target.value;rows();};rows();}
 function rows(){const rows=filtered();root.querySelector('#optRows').innerHTML=rows.length?`<div class="opt-table-wrap"><table><thead><tr><th>Ordem / prioridade</th><th>Produto · cliente</th><th>Setor atual</th><th>Prazo</th><th>Pronta / produção finalizada</th><th>Situação</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><span class="opt-op">OP ${esc(o.op)}</span><br><span class="opt-muted">${o.urgent?'● Urgente · ':''}${o.score} pontos</span></td><td>${esc(o.name)}<br><span class="opt-muted">${esc(o.client)}</span></td><td>${esc(names[o.sector]||o.sector)}</td><td>${date(o.due)}</td><td>${o.readyAt?date(o.readyAt):'Sem previsão'}</td><td><span class="opt-badge ${o.risk}">${risks[o.risk]}</span></td><td><button data-op="${esc(o.id)}">Detalhes</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="opt-empty">Nenhuma OP neste filtro.</div>';bindDetails();}
 function bindDetails(){root.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>detail(b.dataset.op));}
 function capacity(v){v.innerHTML=`<h2>Demanda restante × capacidade de hoje</h2><p class="opt-muted">As passagens de revisão, amostras e análise disputam a mesma equipe de laboratório ou coloração. A demanda inclui etapas futuras; a agenda mostra as passagens previstas para hoje.</p><div class="opt-grid opt-section">${data.capacity.map(p=>`<article class="opt-card"><div class="opt-load-head"><span>${esc(p.label)}</span><strong>${p.loadPercent==null?'Sem capacidade':p.loadPercent+'%'}</strong></div><div class="opt-bar ${p.bottleneck?'warn':''}"><span style="width:${Math.min(100,p.loadPercent||0)}%"></span></div><p>${mins(p.backlogMinutes)} de demanda / ${mins(p.availableMinutes)} disponíveis hoje</p><p class="opt-muted">${mins(p.scheduledMinutes)} programadas hoje · ${p.capacity} recurso(s)</p>${p.bottleneck?'<span class="opt-badge atencao">Demanda excede o dia</span>':''}<div class="opt-section">${p.today.length?p.today.map(t=>`<p class="opt-muted"><button data-op="${esc(t.id)}">OP ${esc(t.op)}</button> ${date(t.start)} → ${date(t.end)}<br>${esc(names[t.sector])}</p>`).join(''):'<p class="opt-muted">Sem passagens previstas hoje.</p>'}</div></article>`).join('')}</div>`;bindDetails();}
 function recommend(v){const c=data.comparison;v.innerHTML=`<h2>Reprogramação sugerida</h2><div class="opt-card"><p>OPs com conclusão após o prazo: <strong>${c.fifoLate} na ordem de chegada → ${c.smartLate} na fila inteligente</strong>.</p><p class="opt-muted">Atraso acumulado previsto: ${mins(c.fifoTardiness)} → ${mins(c.smartTardiness)}. Heurística, sem garantia de solução ótima. A comparação inclui o impacto sobre todas as OPs programáveis.</p></div><div class="opt-list opt-section">${data.recommendations.map(r=>`<article class="opt-card opt-recommend"><div class="opt-inline"><strong>${esc(r.message)}</strong>${r.id?`<button data-op="${esc(r.id)}">Revisar OP</button>`:''}</div><p class="opt-muted">${esc(r.basis)}${r.minutesSaved?` · Antecipação estimada de ${mins(r.minutesSaved)}.`:''}</p></article>`).join('')||'<p class="opt-empty">Sem recomendações nesta atualização.</p>'}</div><p class="opt-muted">Para testar equipe ou expediente, abra Capacidade & regras e simule. Ajustes de prioridade ficam no plano do PCP; a sequência física continua sendo confirmada no FactoryFlow.</p>`;bindDetails();}
 function times(v){const rows=data.queue.flatMap(o=>o.history.map(h=>({...h,op:o.op,id:o.id})));v.innerHTML=`<h2>Tempo real por passagem</h2><p class="opt-muted">Medições reaproveitadas do relatório do FactoryFlow, com pausas e expediente real. Sem registro, o tempo permanece desconhecido. Lead time corrido pode ser consultado em Detalhes da OP.</p>${rows.length?`<div class="opt-table-wrap"><table><thead><tr><th>OP / setor</th><th>Entrada</th><th>Saída</th><th>Trabalho</th><th>Pausa</th><th>Fila / ociosidade</th><th>Total útil</th></tr></thead><tbody>${rows.map(h=>`<tr><td><button data-op="${esc(h.id)}">${esc(h.op)}</button> ${esc(names[h.sector]||h.sector)}</td><td>${date(h.enteredAt)}</td><td>${h.leftAt?date(h.leftAt):'Em andamento'}</td><td>${mins(h.workedMs/60000)}</td><td>${mins(h.pausedMs/60000)}</td><td>${mins(h.idleMs/60000)}</td><td>${mins(h.totalMs/60000)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="opt-empty">Ainda não há medições de etapa disponíveis.</p>'}`;bindDetails();}
 function settings(v){const c=data.config;v.innerHTML=`<h2>Capacidade e calendário da unidade</h2><p class="opt-muted">Recurso = uma OP processada por vez. Valores iniciais são hipóteses até serem calibrados pela equipe. O calendário de previsão é independente dos eventos reais de expediente.</p><form id="optConfig" class="opt-form opt-section">${Object.entries(c.capacity).map(([p,n])=>`<label>${esc(names[p]||'Envase')} · recursos paralelos<input type="number" min="0" max="30" step="1" name="cap_${p}" value="${n}" required></label>`).join('')}<label>Intervalos (HH:MM–HH:MM; separados por vírgula)<input name="windows" value="${c.windows.map(w=>w.map(n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')).join('-')).join(', ')}" required></label><label>Dias (0 domingo, 1 segunda … 6 sábado)<input name="weekdays" value="${c.weekdays.join(',')}" required></label><label>Feriados (AAAA-MM-DD, separados por vírgula)<input name="holidays" value="${esc(c.holidays.join(','))}"></label><label>Margem de atenção (minutos úteis)<input type="number" name="riskBufferMinutes" value="${c.riskBufferMinutes}" min="0" max="10080" required></label><details class="opt-wide"><summary>Tempos previstos sem histórico suficiente (minutos)</summary><div class="opt-form opt-section">${Object.entries(c.durations).map(([p,n])=>`<label>${esc(names[p])}<input type="number" name="dur_${p}" value="${n}" min="1" max="10080" required></label>`).join('')}</div></details><div class="opt-tools opt-wide"><button type="submit" class="opt-primary">Simular capacidade</button><button type="button" id="optSaveConfig">Salvar configuração</button></div></form><div class="opt-card opt-section"><strong>Integrações detectadas</strong><p>FactoryFlow: ${data.integrations?.factoryflow?'disponível':'não conectado'} · CQVISION: ${data.integrations?.cqvision?'disponível':'não conectado'} · P&D: ${data.integrations?.paintlab?'disponível':'não conectado'}</p><p class="opt-muted">CQVISION cruza a OP exata; P&D cruza op_code somente quando o vínculo é único. Nenhuma aprovação de qualidade ou de fórmula é criada por este painel.</p></div>`;
 function read(){const f=new FormData(v.querySelector('form')),config=structuredClone(c);for(const p in c.capacity)config.capacity[p]=Number(f.get('cap_'+p));for(const p in c.durations)config.durations[p]=Number(f.get('dur_'+p));config.windows=String(f.get('windows')).split(',').map(w=>w.trim().split('-').map(t=>{if(!/^\d{2}:\d{2}$/.test(t.trim()))throw Error('Use HH:MM-HH:MM nos intervalos');const [h,m]=t.trim().split(':').map(Number);if(h>23||m>59)throw Error('Horário inválido');return h*60+m;}));config.weekdays=String(f.get('weekdays')).split(',').map(Number);config.holidays=String(f.get('holidays')).split(',').map(x=>x.trim()).filter(Boolean);config.riskBufferMinutes=Number(f.get('riskBufferMinutes'));return config;}
 v.querySelector('form').onsubmit=e=>{e.preventDefault();action(async()=>{data=await api('/simulate','POST',{config:read()});simulated=true;tab='capacity';render();message('Simulação calculada. Consulte os riscos e a reprogramação; nada foi salvo.');});};v.querySelector('#optSaveConfig').onclick=()=>action(async()=>{if(!v.querySelector('form').reportValidity())return;await api('/config','PUT',{config:read(),revision:data.revision});await load();message('Capacidade salva e plano recalculado.');});}
 function detail(id){const o=data.queue.find(o=>o.id===id);if(!o)return;const dlg=root.querySelector('#optDetail');dlg.innerHTML=`<button class="opt-close" id="optClose">Fechar</button><span class="opt-eyebrow">${esc(names[o.sector]||o.sector)}</span><h2>OP ${esc(o.op)} · ${esc(o.name)}</h2><p>${esc(o.client)} · ${esc(o.quantity)} (quantidade ERP)</p><p><span class="opt-badge ${o.risk}">${risks[o.risk]}</span> · Lead time corrido ${mins(o.leadMinutes)}${o.done?'':' até agora'}</p><p class="opt-muted">Prazo ${date(o.due)} · Pronta ${date(o.readyAt)}</p>${o.reason?`<div class="opt-notice">${esc(o.reason)}</div>`:''}<h2 class="opt-section">Roteiro restante</h2><div class="opt-list">${o.steps.map(t=>`<div class="opt-card">${esc(names[t.sector])} · ${mins(t.minutes)} <span class="opt-muted">${esc(t.source)} · ${t.samples} amostras</span></div>`).join('')||'<p class="opt-muted">Sem operação produtiva restante.</p>'}</div><p class="opt-muted">CQVISION: ${esc(o.quality?.resultado||'sem análise vinculada')} · P&D: ${esc(o.pd?.status||'sem vínculo exato')}</p><details class="opt-section"><summary>Ajustar planejamento desta OP</summary><form id="optOrder" class="opt-form opt-section"><label>Prioridade<select name="priority">${[['normal','Normal'],['urgent','Urgente'],['sameday','Mesmo dia']].map(([k,l])=>`<option value="${k}" ${o.priority===k?'selected':''}>${l}</option>`).join('')}</select></label><label>Ajuste PCP (0–500 pontos)<input name="boost" type="number" min="0" max="500" value="${o.settings?.boost||0}" required></label><label class="opt-wide">Bloqueio manual (vazio remove este bloqueio)<input name="blockReason" maxlength="500" value="${esc(o.settings?.blockReason||'')}"></label><label class="opt-wide">Dependências (IDs dos lotes, separados por vírgula)<input name="dependencies" value="${esc(o.deps.join(','))}"></label><label class="opt-wide">Roteiro restante (chaves de setor, em ordem; vazio usa fluxo padrão)<textarea name="route">${esc((o.settings?.route||[]).join(','))}</textarea><span>Chaves: ${esc(Object.keys(names).join(', '))}. Para amostras, confirme a passagem atual e os retornos.</span></label><p class="opt-muted opt-wide">ID deste lote: ${esc(o.id)}. O ajuste afeta o planejamento, sem movimentar o lote ou ignorar bloqueios do FactoryFlow/CQVISION.</p><button class="opt-primary" type="submit">Salvar ajuste PCP</button><p id="optOrderError" role="alert"></p></form></details>`;
 dlg.querySelector('#optClose').onclick=()=>dlg.close();dlg.querySelector('form').onsubmit=e=>{e.preventDefault();action(async()=>{try{const f=new FormData(e.target);await api('/orders/'+encodeURIComponent(id),'PUT',{priority:f.get('priority'),boost:Number(f.get('boost')),blockReason:f.get('blockReason'),dependencies:String(f.get('dependencies')).split(',').map(x=>x.trim()).filter(Boolean),route:String(f.get('route')).trim()?String(f.get('route')).split(',').map(x=>x.trim()):null,revision:o.settings?.revision||0});dlg.close();await load();message('Ajuste PCP salvo.');}catch(err){dlg.querySelector('#optOrderError').textContent=err.message;}});};dlg.showModal();}
})();
